{% set name = "litepcie" %}
{% set version = "2023.04" %}
{% set sha256 = "4a79102facdbcf9ec0641f15873f1aa77bd92285717e99cc73c769c82344091d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  entry_points:
    - litepcie_gen = litepcie.gen:main

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - litex
    - packaging
    - pyyaml

test:
  imports:
    - litepcie
  commands:
    - litepcie_gen --help

about:
  home: https://github.com/enjoy-digital/litepcie
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable PCIe core
  description: Small footprint and configurable PCIe core
  dev_url: https://github.com/enjoy-digital/litepcie

extra:
  recipe-maintainers:
    - enjoy-digital
    - timkpaine
