{% set name = "litepcie" %}
{% set version = "2024.08" %}
{% set sha256 = "9fe6b3cf7e26ca63e734fe9056138085a495203588bc2f9269934bc50ab3d36c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - litepcie_gen = litepcie.gen:main

requirements:
  host:
    - python >=3.7,<3.12
    - pip
    - setuptools
  run:
    - python >=3.7,<3.12
    - litex ={{ version }}
    - packaging
    - pyyaml

test:
  imports:
    - litepcie
  commands:
    - litepcie_gen --help

about:
  home: https://github.com/enjoy-digital/litepcie
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable PCIe core
  description: Small footprint and configurable PCIe core
  dev_url: https://github.com/enjoy-digital/litepcie

extra:
  recipe-maintainers:
    - enjoy-digital
    - timkpaine
