{% set name = "litepcie" %}
{% set version = "2023.12" %}
{% set sha256 = "48bb76c603a69853294c9dac87cdec58bfbb7255b7f59e74f2e9b6c8f8ae0f3f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/enjoy-digital/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation
  entry_points:
    - litepcie_gen = litepcie.gen:main

requirements:
  host:
    - python >=3.7,<3.12
    - pip
  run:
    - python >=3.7,<3.12
    - litex >=2023.08
    - packaging
    - pyyaml

test:
  imports:
    - litepcie
  commands:
    - litepcie_gen --help

about:
  home: https://github.com/enjoy-digital/litepcie
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable PCIe core
  description: Small footprint and configurable PCIe core
  dev_url: https://github.com/enjoy-digital/litepcie

extra:
  recipe-maintainers:
    - enjoy-digital
    - timkpaine
